services:
  registry:
    image: registry:latest
    restart: unless-stopped
    environment:
      OTEL_TRACES_EXPORTER: none
    volumes:
      # Mount the data directory
      - ./registry/data:/var/lib/registry
      - ./registry.config.yaml:/etc/distribution/config.yml
    ports:
      - 5050:5000
  registry-ui:
    image: quiq/registry-ui
    restart: unless-stopped
    environment:
      REGISTRY_HOSTNAME: registry:5000
      REGISTRY_INSECURE: true
      ACCESS_CONTROL_ANYONE_CAN_DELETE_TAGS: true
    ports:
      - 5080:8000