version: 0.1
log:
  accesslog:
    disabled: true
  level: info
  formatter: text
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
  cache:
    blobdescriptor: inmemory
  maintenance:
    uploadpurging:
      enabled: true
      age: 24h
      interval: 1h
      dryrun: false
    readonly:
      enabled: false
  tag:
    concurrencylimit: 8
  delete:
    enabled: true
tags:
  maxtags: 1000
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: [http://127.0.0.1:5080]
    Access-Control-Allow-Methods: [HEAD,GET,OPTIONS,DELETE]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Allow-Headers: [Authorization,Accept,Cache-Control]
    Access-Control-Expose-Headers: [Docker-Content-Digest]
prometheus:
  enabled: false